/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MateriaSubjectIdIndexRouteImport } from './routes/materia.$subjectId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaSubjectIdIndexRoute = MateriaSubjectIdIndexRouteImport.update({
  id: '/materia/$subjectId/',
  path: '/materia/$subjectId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/materia/$subjectId/': typeof MateriaSubjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/materia/$subjectId': typeof MateriaSubjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/materia/$subjectId/': typeof MateriaSubjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/materia/$subjectId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/materia/$subjectId'
  id: '__root__' | '/' | '/materia/$subjectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MateriaSubjectIdIndexRoute: typeof MateriaSubjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materia/$subjectId/': {
      id: '/materia/$subjectId/'
      path: '/materia/$subjectId'
      fullPath: '/materia/$subjectId/'
      preLoaderRoute: typeof MateriaSubjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MateriaSubjectIdIndexRoute: MateriaSubjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
